spring:
    port: ${PORT}
    datasource:
        driverClassName: org.postgresql.Driver
        password: password
        url: jdbc:postgresql://${SQL_HOST:localhost}:${SQL_PORT:15432}/${SQL_DB:apollo}
        username: root
    jpa:
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                default_schema: aquarius
                format_sql: true
        hibernate:
            ddl-auto: none
        name: todolist
    liquibase:
        default-schema: aquarius
